apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-trackmate-cron-interface
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: kaniko-trackmate-cron-interface
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: [
          "--context=/godata/pipelines/trackmate-cron-interface",
          "--dockerfile=/godata/pipelines/trackmate-cron-interface/Dockerfile",
          "--destination=quay.io/14west/trackmate-cron-interface:1.14.2"
        ]
        volumeMounts:
        - mountPath: /godata
          name: gocdagent-data
        - mountPath: /kaniko/.docker/config.json
          name: docker-creds
          subPath: config.json
        env:
        - name: DESITINATION
          value: quay.io/14west/trackmate-cron-interface:1.14.2
      restartPolicy: Never   
      volumes:
      - name: gocdagent-data
        persistentVolumeClaim:
          claimName: gocdagent-node-and-go
      - name: docker-creds
        configMap:
          defaultMode: 420
          name: configcontent
      backoffLimit: 1
